<a href="https://colab.research.google.com/github/yrhutu21/Deep_Learning_Projects/blob/main/Iris_Training_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
dt = load_iris()

In [ ]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
X,Y = dt.data,dt.target

In [ ]:
dt.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
#i/p layer 4 and hidden layer 30 # hidden layer 30 and 10 #hidden layer 10 and o/p layer 3
model = nn.Sequential (
    nn.Linear(4, 30),
    nn.ReLU(),
    nn.Linear(30, 10),
    nn.ReLU(),
    nn.Linear(10, 3),
    #nn.Softmax(dim = 1)
)

In [ ]:
X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [ ]:
#model(X)

tensor([[0.2524, 0.4392, 0.3083],
        [0.2511, 0.4386, 0.3104],
        [0.2521, 0.4382, 0.3097],
        [0.2518, 0.4410, 0.3072],
        [0.2521, 0.4395, 0.3084],
        [0.2521, 0.4446, 0.3034],
        [0.2515, 0.4405, 0.3080],
        [0.2522, 0.4408, 0.3069],
        [0.2518, 0.4398, 0.3084],
        [0.2512, 0.4394, 0.3094],
        [0.2527, 0.4404, 0.3069],
        [0.2520, 0.4424, 0.3056],
        [0.2515, 0.4383, 0.3101],
        [0.2518, 0.4352, 0.3130],
        [0.2538, 0.4351, 0.3110],
        [0.2513, 0.4451, 0.3036],
        [0.2529, 0.4382, 0.3089],
        [0.2524, 0.4396, 0.3079],
        [0.2517, 0.4429, 0.3054],
        [0.2519, 0.4415, 0.3066],
        [0.2501, 0.4415, 0.3084],
        [0.2520, 0.4418, 0.3062],
        [0.2510, 0.4371, 0.3119],
        [0.2512, 0.4423, 0.3065],
        [0.2503, 0.4454, 0.3044],
        [0.2494, 0.4400, 0.3106],
        [0.2519, 0.4428, 0.3054],
        [0.2524, 0.4406, 0.3069],
        [0.2527, 0.4390, 0.3083],
        [0.251

In [ ]:
#torch.argmax(model(X) , dim=1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1])

In [ ]:
lossfn = nn.CrossEntropyLoss()
optSgd = optim.SGD(model.parameters(), lr =0.01)

Training


In [ ]:
for _ in range(200):
    optSgd.zero_grad()
    Yp = model(X)
    loss = lossfn(Yp, Y)
    loss.backward()
    optSgd.step()

    print(loss.item())

1.132391333580017
1.1239960193634033
1.1171371936798096
1.111205816268921
1.1057120561599731
1.1006332635879517
1.096120834350586
1.0921998023986816
1.0885919332504272
1.085184097290039
1.081929326057434
1.0788114070892334
1.0758142471313477
1.0729341506958008
1.0701429843902588
1.0674386024475098
1.064823865890503
1.0622756481170654
1.0597867965698242
1.057357907295227
1.0549782514572144
1.0526466369628906
1.0503562688827515
1.0481058359146118
1.0458908081054688
1.0437067747116089
1.0415505170822144
1.0394165515899658
1.0373058319091797
1.0352157354354858
1.0331428050994873
1.031084656715393
1.0290391445159912
1.027005672454834
1.024979829788208
1.0229641199111938
1.020954966545105
1.018949270248413
1.0169459581375122
1.0149457454681396
1.0129469633102417
1.0109463930130005
1.0089436769485474
1.006937861442566
1.004928708076477
1.0029140710830688
1.0008924007415771
0.9988630414009094
0.9968249797821045
0.9947797656059265
0.9927238821983337
0.9906573295593262
0.9885814189910889
0.98650

Inference

In [ ]:
ynewp = model(X)

In [ ]:
sftout = torch.softmax(ynewp,dim=1)

In [ ]:
torch.argmax(sftout, dim=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2])

Batches

In [81]:
from torch.utils.data import DataLoader

In [82]:
df = pd.DataFrame(X)

In [83]:
df

,0,1,2,3
0,5.7,3.8,1.7,0.3
1,6.9,3.2,5.7,2.3
2,6.0,2.2,5.0,1.5
3,5.5,4.2,1.4,0.2
4,6.3,3.3,4.7,1.6
5,6.3,3.4,5.6,2.4
6,6.7,3.3,5.7,2.5
7,5.7,2.6,3.5,1.0
8,6.0,3.0,4.8,1.8
9,5.2,4.1,1.5,0.1


In [ ]:
#[X,Y]

[tensor([[5.1000, 3.5000, 1.4000, 0.2000],
         [4.9000, 3.0000, 1.4000, 0.2000],
         [4.7000, 3.2000, 1.3000, 0.2000],
         [4.6000, 3.1000, 1.5000, 0.2000],
         [5.0000, 3.6000, 1.4000, 0.2000],
         [5.4000, 3.9000, 1.7000, 0.4000],
         [4.6000, 3.4000, 1.4000, 0.3000],
         [5.0000, 3.4000, 1.5000, 0.2000],
         [4.4000, 2.9000, 1.4000, 0.2000],
         [4.9000, 3.1000, 1.5000, 0.1000],
         [5.4000, 3.7000, 1.5000, 0.2000],
         [4.8000, 3.4000, 1.6000, 0.2000],
         [4.8000, 3.0000, 1.4000, 0.1000],
         [4.3000, 3.0000, 1.1000, 0.1000],
         [5.8000, 4.0000, 1.2000, 0.2000],
         [5.7000, 4.4000, 1.5000, 0.4000],
         [5.4000, 3.9000, 1.3000, 0.4000],
         [5.1000, 3.5000, 1.4000, 0.3000],
         [5.7000, 3.8000, 1.7000, 0.3000],
         [5.1000, 3.8000, 1.5000, 0.3000],
         [5.4000, 3.4000, 1.7000, 0.2000],
         [5.1000, 3.7000, 1.5000, 0.4000],
         [4.6000, 3.6000, 1.0000, 0.2000],
         [5

In [84]:
df['Y'] = Y

In [85]:
data = torch.tensor(df.to_numpy())

In [86]:
batches = DataLoader(data, batch_size=10,shuffle = True)

In [87]:
for batch in batches:
  #print(batch)
  #batch = torch.tensor(batch)
  X = batch[:, :-1]
  Y = batch[:, -1]
  print(X,Y)


tensor([[6.3000, 3.4000, 5.6000, 2.4000],
        [6.3000, 3.3000, 4.7000, 1.6000],
        [6.9000, 3.2000, 5.7000, 2.3000],
        [6.7000, 3.3000, 5.7000, 2.5000],
        [5.2000, 4.1000, 1.5000, 0.1000],
        [5.5000, 4.2000, 1.4000, 0.2000],
        [5.7000, 2.6000, 3.5000, 1.0000],
        [5.7000, 3.8000, 1.7000, 0.3000],
        [6.0000, 3.0000, 4.8000, 1.8000],
        [6.0000, 2.2000, 5.0000, 1.5000]], dtype=torch.float64) tensor([2., 1., 2., 2., 0., 0., 1., 0., 2., 2.], dtype=torch.float64)


In [88]:
from torch.utils.data import DataLoader

In [89]:
df = pd.DataFrame(X)

In [90]:
df

,0,1,2,3
0,6.3,3.4,5.6,2.4
1,6.3,3.3,4.7,1.6
2,6.9,3.2,5.7,2.3
3,6.7,3.3,5.7,2.5
4,5.2,4.1,1.5,0.1
5,5.5,4.2,1.4,0.2
6,5.7,2.6,3.5,1.0
7,5.7,3.8,1.7,0.3
8,6.0,3.0,4.8,1.8
9,6.0,2.2,5.0,1.5


In [91]:
df['Y'] = Y

In [92]:
data = torch.tensor(df.to_numpy())

In [93]:
model1 = nn.Sequential (
    nn.Linear(4, 30),
    nn.ReLU(),
    nn.Linear(30, 10),
    nn.ReLU(),
    nn.Linear(10, 3),
    #nn.Softmax(dim = 1)
)

In [94]:
lossfn = nn.CrossEntropyLoss()
batchSgd1 = optim.SGD(model1.parameters(), lr =0.01)

In [72]:
batches = DataLoader(data, batch_size=10,shuffle = True)

In [98]:
model1.train()
for epoch in range(200):
  batch_loss = 0
  for i, batch in enumerate(batches):
    batch_X = batch[:, :-1].float()
    batch_Y = batch[:, -1].long()

    batchSgd1.zero_grad()
    batch_Yp = model1(batch_X)
    loss = lossfn(batch_Yp, batch_Y)
    loss.backward()
    batchSgd1.step()
    batch_loss = batch_loss + loss.item()
    print(f"Epoch {epoch+1}:  Total Loss = {batch_loss}")



Epoch 1:  Total Loss = 0.2587844729423523
Epoch 2:  Total Loss = 0.25816598534584045
Epoch 3:  Total Loss = 0.2575470209121704
Epoch 4:  Total Loss = 0.2569308876991272
Epoch 5:  Total Loss = 0.2563157379627228
Epoch 6:  Total Loss = 0.25570088624954224
Epoch 7:  Total Loss = 0.25508707761764526
Epoch 8:  Total Loss = 0.2544736862182617
Epoch 9:  Total Loss = 0.2538609802722931
Epoch 10:  Total Loss = 0.25324946641921997
Epoch 11:  Total Loss = 0.2526378333568573
Epoch 12:  Total Loss = 0.2520276606082916
Epoch 13:  Total Loss = 0.25141769647598267
Epoch 14:  Total Loss = 0.25080907344818115
Epoch 15:  Total Loss = 0.2502003014087677
Epoch 16:  Total Loss = 0.24959306418895721
Epoch 17:  Total Loss = 0.24898603558540344
Epoch 18:  Total Loss = 0.24838025867938995
Epoch 19:  Total Loss = 0.24777451157569885
Epoch 20:  Total Loss = 0.24717023968696594
Epoch 21:  Total Loss = 0.24656608700752258
Epoch 22:  Total Loss = 0.24596352875232697
Epoch 23:  Total Loss = 0.24536089599132538
Epoch 