<a href="https://colab.research.google.com/github/yrhutu21/Deep_Learning_Projects/blob/main/Iris_Training_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
from sklearn.datasets import load_iris

In [39]:
import numpy as np
import pandas as pd

In [40]:
import torch
import torch.nn as nn
import torch.optim as optim

In [41]:
dt = load_iris()

In [42]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [43]:
X,Y = dt.data,dt.target

In [44]:
dt.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [45]:
#i/p layer 4 and hidden layer 30 # hidden layer 30 and 10 #hidden layer 10 and o/p layer 3
model = nn.Sequential (
    nn.Linear(4, 30),
    nn.ReLU(),
    nn.Linear(30, 10),
    nn.ReLU(),
    nn.Linear(10, 3),
    #nn.Softmax(dim = 1)
)

In [46]:
X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [21]:
#model(X)

tensor([[0.2524, 0.4392, 0.3083],
        [0.2511, 0.4386, 0.3104],
        [0.2521, 0.4382, 0.3097],
        [0.2518, 0.4410, 0.3072],
        [0.2521, 0.4395, 0.3084],
        [0.2521, 0.4446, 0.3034],
        [0.2515, 0.4405, 0.3080],
        [0.2522, 0.4408, 0.3069],
        [0.2518, 0.4398, 0.3084],
        [0.2512, 0.4394, 0.3094],
        [0.2527, 0.4404, 0.3069],
        [0.2520, 0.4424, 0.3056],
        [0.2515, 0.4383, 0.3101],
        [0.2518, 0.4352, 0.3130],
        [0.2538, 0.4351, 0.3110],
        [0.2513, 0.4451, 0.3036],
        [0.2529, 0.4382, 0.3089],
        [0.2524, 0.4396, 0.3079],
        [0.2517, 0.4429, 0.3054],
        [0.2519, 0.4415, 0.3066],
        [0.2501, 0.4415, 0.3084],
        [0.2520, 0.4418, 0.3062],
        [0.2510, 0.4371, 0.3119],
        [0.2512, 0.4423, 0.3065],
        [0.2503, 0.4454, 0.3044],
        [0.2494, 0.4400, 0.3106],
        [0.2519, 0.4428, 0.3054],
        [0.2524, 0.4406, 0.3069],
        [0.2527, 0.4390, 0.3083],
        [0.251

In [22]:
#torch.argmax(model(X) , dim=1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1])

In [47]:
lossfn = nn.CrossEntropyLoss()
optSgd = optim.SGD(model.parameters(), lr =0.01)

Training


In [48]:
for _ in range(200):
    optSgd.zero_grad()
    Yp = model(X)
    loss = lossfn(Yp, Y)
    loss.backward()
    optSgd.step()

    print(loss.item())

1.132391333580017
1.1239960193634033
1.1171371936798096
1.111205816268921
1.1057120561599731
1.1006332635879517
1.096120834350586
1.0921998023986816
1.0885919332504272
1.085184097290039
1.081929326057434
1.0788114070892334
1.0758142471313477
1.0729341506958008
1.0701429843902588
1.0674386024475098
1.064823865890503
1.0622756481170654
1.0597867965698242
1.057357907295227
1.0549782514572144
1.0526466369628906
1.0503562688827515
1.0481058359146118
1.0458908081054688
1.0437067747116089
1.0415505170822144
1.0394165515899658
1.0373058319091797
1.0352157354354858
1.0331428050994873
1.031084656715393
1.0290391445159912
1.027005672454834
1.024979829788208
1.0229641199111938
1.020954966545105
1.018949270248413
1.0169459581375122
1.0149457454681396
1.0129469633102417
1.0109463930130005
1.0089436769485474
1.006937861442566
1.004928708076477
1.0029140710830688
1.0008924007415771
0.9988630414009094
0.9968249797821045
0.9947797656059265
0.9927238821983337
0.9906573295593262
0.9885814189910889
0.98650

Inference

In [50]:
ynewp = model(X)

In [51]:
sftout = torch.softmax(ynewp,dim=1)

In [52]:
torch.argmax(sftout, dim=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2])

Batches